services:
  backend:
    build: ./backend
    ports:
      - "5050:5050" 
    networks:
      - tetris_network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - tetris_network

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - tetris_network
    volumes:
      - mongo-data:/data/db  

networks:
  tetris_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  